<?php


 function autoload_8da5d386c6569a43e266f80121cf941e($class)
{
    $classes = array(
        'DdD\Sale\SaleService' => __DIR__ .'/SaleService.php',
        'DdD\Sale\ArrayOfKeyValueOfdateTimeArrayOfKeyValueOfintdecimalty7Ep6D1' => __DIR__ .'/ArrayOfKeyValueOfdateTimeArrayOfKeyValueOfintdecimalty7Ep6D1.php',
        'DdD\Sale\KeyValueOfdateTimeArrayOfKeyValueOfintdecimalty7Ep6D1' => __DIR__ .'/KeyValueOfdateTimeArrayOfKeyValueOfintdecimalty7Ep6D1.php',
        'DdD\Sale\ArrayOfKeyValueOfintdecimal' => __DIR__ .'/ArrayOfKeyValueOfintdecimal.php',
        'DdD\Sale\KeyValueOfintdecimal' => __DIR__ .'/KeyValueOfintdecimal.php',
        'DdD\Sale\ArrayOfKeyValueOfdateTimeKeyFigureszJ_S5Vm7C' => __DIR__ .'/ArrayOfKeyValueOfdateTimeKeyFigureszJ_S5Vm7C.php',
        'DdD\Sale\KeyValueOfdateTimeKeyFigureszJ_S5Vm7C' => __DIR__ .'/KeyValueOfdateTimeKeyFigureszJ_S5Vm7C.php',
        'DdD\Sale\ArrayOfKeyValueOfdateTimeArrayOfKeyFigureszJ_S5Vm7C' => __DIR__ .'/ArrayOfKeyValueOfdateTimeArrayOfKeyFigureszJ_S5Vm7C.php',
        'DdD\Sale\KeyValueOfdateTimeArrayOfKeyFigureszJ_S5Vm7C' => __DIR__ .'/KeyValueOfdateTimeArrayOfKeyFigureszJ_S5Vm7C.php',
        'DdD\Sale\ArrayOfKeyValueOfdateTimeTransactionHeaderzJ_S5Vm7C' => __DIR__ .'/ArrayOfKeyValueOfdateTimeTransactionHeaderzJ_S5Vm7C.php',
        'DdD\Sale\KeyValueOfdateTimeTransactionHeaderzJ_S5Vm7C' => __DIR__ .'/KeyValueOfdateTimeTransactionHeaderzJ_S5Vm7C.php',
        'DdD\Sale\ArrayOfstring' => __DIR__ .'/ArrayOfstring.php',
        'DdD\Sale\Sale' => __DIR__ .'/Sale.php',
        'DdD\Sale\ArrayOfItemLine' => __DIR__ .'/ArrayOfItemLine.php',
        'DdD\Sale\ItemLine' => __DIR__ .'/ItemLine.php',
        'DdD\Sale\ItemLineType' => __DIR__ .'/ItemLineType.php',
        'DdD\Sale\ArrayOfPaymentLine' => __DIR__ .'/ArrayOfPaymentLine.php',
        'DdD\Sale\PaymentLine' => __DIR__ .'/PaymentLine.php',
        'DdD\Sale\PaymentLineType' => __DIR__ .'/PaymentLineType.php',
        'DdD\Sale\SaleType' => __DIR__ .'/SaleType.php',
        'DdD\Sale\Status' => __DIR__ .'/Status.php',
        'DdD\Sale\ArrayOfSale' => __DIR__ .'/ArrayOfSale.php',
        'DdD\Sale\ArrayOfStatus' => __DIR__ .'/ArrayOfStatus.php',
        'DdD\Sale\Retry' => __DIR__ .'/Retry.php',
        'DdD\Sale\RetryRetryOption' => __DIR__ .'/RetryRetryOption.php',
        'DdD\Sale\SaleSum' => __DIR__ .'/SaleSum.php',
        'DdD\Sale\KeyFigures' => __DIR__ .'/KeyFigures.php',
        'DdD\Sale\ArrayOfKeyFigures' => __DIR__ .'/ArrayOfKeyFigures.php',
        'DdD\Sale\OrderableRowType' => __DIR__ .'/OrderableRowType.php',
        'DdD\Sale\TransactionHeader' => __DIR__ .'/TransactionHeader.php',
        'DdD\Sale\ArrayOfTransactionRow' => __DIR__ .'/ArrayOfTransactionRow.php',
        'DdD\Sale\TransactionRow' => __DIR__ .'/TransactionRow.php',
        'DdD\Sale\TransactionRowType' => __DIR__ .'/TransactionRowType.php',
        'DdD\Sale\ResponseMessage' => __DIR__ .'/ResponseMessage.php',
        'DdD\Sale\CertificateResponse' => __DIR__ .'/CertificateResponse.php',
        'DdD\Sale\CertificateStatus' => __DIR__ .'/CertificateStatus.php',
        'DdD\Sale\CertificateType' => __DIR__ .'/CertificateType.php',
        'DdD\Sale\ArrayOfCertificateResponse' => __DIR__ .'/ArrayOfCertificateResponse.php',
        'DdD\Sale\ArrayOfWebOrder' => __DIR__ .'/ArrayOfWebOrder.php',
        'DdD\Sale\WebOrder' => __DIR__ .'/WebOrder.php',
        'DdD\Sale\SaveSale' => __DIR__ .'/SaveSale.php',
        'DdD\Sale\SaveSaleResponse' => __DIR__ .'/SaveSaleResponse.php',
        'DdD\Sale\SaveSale_Bulk' => __DIR__ .'/SaveSale_Bulk.php',
        'DdD\Sale\SaveSale_BulkResponse' => __DIR__ .'/SaveSale_BulkResponse.php',
        'DdD\Sale\RetrySales' => __DIR__ .'/RetrySales.php',
        'DdD\Sale\RetrySalesResponse' => __DIR__ .'/RetrySalesResponse.php',
        'DdD\Sale\SaleCouldNotBeDelivered' => __DIR__ .'/SaleCouldNotBeDelivered.php',
        'DdD\Sale\SaleCouldNotBeDeliveredResponse' => __DIR__ .'/SaleCouldNotBeDeliveredResponse.php',
        'DdD\Sale\StartSale' => __DIR__ .'/StartSale.php',
        'DdD\Sale\StartSaleResponse' => __DIR__ .'/StartSaleResponse.php',
        'DdD\Sale\GetSales' => __DIR__ .'/GetSales.php',
        'DdD\Sale\GetSalesResponse' => __DIR__ .'/GetSalesResponse.php',
        'DdD\Sale\GetSalesSinceDateTime' => __DIR__ .'/GetSalesSinceDateTime.php',
        'DdD\Sale\GetSalesSinceDateTimeResponse' => __DIR__ .'/GetSalesSinceDateTimeResponse.php',
        'DdD\Sale\GetKeyFigures' => __DIR__ .'/GetKeyFigures.php',
        'DdD\Sale\GetKeyFiguresResponse' => __DIR__ .'/GetKeyFiguresResponse.php',
        'DdD\Sale\GetKeyFiguresByTerminal' => __DIR__ .'/GetKeyFiguresByTerminal.php',
        'DdD\Sale\GetKeyFiguresByTerminalResponse' => __DIR__ .'/GetKeyFiguresByTerminalResponse.php',
        'DdD\Sale\GetTransactions' => __DIR__ .'/GetTransactions.php',
        'DdD\Sale\GetTransactionsResponse' => __DIR__ .'/GetTransactionsResponse.php',
        'DdD\Sale\GetTransactionsPaged' => __DIR__ .'/GetTransactionsPaged.php',
        'DdD\Sale\GetTransactionsPagedResponse' => __DIR__ .'/GetTransactionsPagedResponse.php',
        'DdD\Sale\GetTransactionsSinceLastNumber' => __DIR__ .'/GetTransactionsSinceLastNumber.php',
        'DdD\Sale\GetTransactionsSinceLastNumberResponse' => __DIR__ .'/GetTransactionsSinceLastNumberResponse.php',
        'DdD\Sale\GetCustomerTransactions' => __DIR__ .'/GetCustomerTransactions.php',
        'DdD\Sale\GetCustomerTransactionsResponse' => __DIR__ .'/GetCustomerTransactionsResponse.php',
        'DdD\Sale\GetSpecificTransaction' => __DIR__ .'/GetSpecificTransaction.php',
        'DdD\Sale\GetSpecificTransactionResponse' => __DIR__ .'/GetSpecificTransactionResponse.php',
        'DdD\Sale\GetTransactionsBySupplier' => __DIR__ .'/GetTransactionsBySupplier.php',
        'DdD\Sale\GetTransactionsBySupplierResponse' => __DIR__ .'/GetTransactionsBySupplierResponse.php',
        'DdD\Sale\GetTransactionsSinceLastNumberBySupplier' => __DIR__ .'/GetTransactionsSinceLastNumberBySupplier.php',
        'DdD\Sale\GetTransactionsSinceLastNumberBySupplierResponse' => __DIR__ .'/GetTransactionsSinceLastNumberBySupplierResponse.php',
        'DdD\Sale\GenerateGiftcertificateNumber' => __DIR__ .'/GenerateGiftcertificateNumber.php',
        'DdD\Sale\GenerateGiftcertificateNumberResponse' => __DIR__ .'/GenerateGiftcertificateNumberResponse.php',
        'DdD\Sale\ValidateCertificate' => __DIR__ .'/ValidateCertificate.php',
        'DdD\Sale\ValidateCertificateResponse' => __DIR__ .'/ValidateCertificateResponse.php',
        'DdD\Sale\GetCertificates' => __DIR__ .'/GetCertificates.php',
        'DdD\Sale\GetCertificatesResponse' => __DIR__ .'/GetCertificatesResponse.php',
        'DdD\Sale\SaveWebshopOrder' => __DIR__ .'/SaveWebshopOrder.php',
        'DdD\Sale\SaveWebshopOrderResponse' => __DIR__ .'/SaveWebshopOrderResponse.php',
        'DdD\Sale\GetWebOrders' => __DIR__ .'/GetWebOrders.php',
        'DdD\Sale\GetWebOrdersResponse' => __DIR__ .'/GetWebOrdersResponse.php',
        'DdD\Sale\WebOrdersReadyForPick' => __DIR__ .'/WebOrdersReadyForPick.php',
        'DdD\Sale\WebOrdersReadyForPickResponse' => __DIR__ .'/WebOrdersReadyForPickResponse.php',
        'DdD\Sale\WebPosParkedReceipts' => __DIR__ .'/WebPosParkedReceipts.php',
        'DdD\Sale\WebPosParkedReceiptsResponse' => __DIR__ .'/WebPosParkedReceiptsResponse.php',
        'DdD\Sale\RemoveWebPosParkedReceipts' => __DIR__ .'/RemoveWebPosParkedReceipts.php',
        'DdD\Sale\RemoveWebPosParkedReceiptsResponse' => __DIR__ .'/RemoveWebPosParkedReceiptsResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_8da5d386c6569a43e266f80121cf941e');

// Do nothing. The rest is just leftovers from the code generation.
{
}
